### ISSUE TITLE
Rub Ell hizb

### ISSUE THREAD

**Issue by jedimaster5459** [rockneverdies55/quran-epub#1]
Would it be possible to add numbers or dots to rub el hizb to aid in recitation?
I've attached a screenshot with an example. May Allah reward you for your efforts.
![Screenshot 2023-11-13 at 9 19 08 AM](https://github.com/rockneverdies55/quran-epub/assets/123992090/b10dbe23-58f4-4c91-99f7-113b78a5c8cd)

**Comment by rockneverdies55** [comment]
Glad to hear that you find it useful. May Allah be pleased with you. I will see what I can do about the rub el-hizb signs.

**Comment by jedimaster5459** [comment]
I've added 1/8th fraction markers for each rub el hizb. I also removed the bismilallah from surah taubah (chapter 10) as most mushafs have it as part of the previous surah.  I did this for the quran_en file only, see below link. Hope this helps. Thank you again for this epub. salaam.

[https://mega.nz/file/1DVmDDZQ#NOYrqaRALCdpPFb7W_HYGcflgUiiHCBjsyDrStpICw4](url)

**Comment by rockneverdies55** [comment]
The link doesn't go anywhere

**Comment by jedimaster5459** [comment]
https://mega.nz/file/1DVmDDZQ#NOYrqaRALCdpPFb7W_HYGcflgUiiHCBjsyDrStpICw4

Copy and paste into browser if doesn’t open upon clicking

**Comment by rockneverdies55** [comment]
Release 005 is now including the hizb signs. Thanks again.

**Comment by rockneverdies55** [comment]
Closing as completed.
